#!/bin/bash

API_URL="https://pokeapi.co/api/v2/pokemon"

DELAY=2

LIST=(Bulbasaur Ivysaur Venusaur Charmander Charmeleon)

for name in "${LIST[@]}"; do
    echo "Fetching data for $name"

    details=$(curl -s "${API_URL}/${name}")

    if [ $? -ne 0 ] || [ -z "$details" ]; then
        echo "Unsuccessful"
        continue
    fi

    sanitize_name=$(echo "$name" | sed 's/[^a-zA-Z0-9._-]/_/g')
    filename="${sanitize_name}.json"

    echo "$details" > "$filename"
    echo "Created file: $filename"

    echo "Sleeping for $DELAY seconds ..."
    sleep "$DELAY"
done

echo Done