#!/bin/bash

API_URL="https://pokeapi.co/api/v2/pokemon"

DELAY=2

MAX_RETRIES=3

LIST=(bulbasaur ivysaur venusaur charmander charmeleon)

for name in "${LIST[@]}"; do
    echo "Fetching data for $name"

    retries=0
    success=false

    while [ $retries -lt $MAX_RETRIES ]; do
        details=$(curl -s -f "${API_URL}/${name}")

    if [ $? -eq 0 ] || [ -z "$details" ]; then
        success=true
        break
    else
        retries=$((retries+1))
        echo "Attempt $retries failed for $name. Retrying in 2 seconds"
        sleep 2
    fi
done

    if [ "$success" = false ]; then
        echo "Failed to fetch data for $name after $MAX_RETRIES"
        echo "Skipping $name ..."
        continue
    fi
    sanitize_name=$(echo "$name" | sed 's/[^a-zA-Z0-9._-]/_/g')
    filename="${sanitize_name}.json"

    echo "$details" > "$filename"
    echo "Created file: $filename"

    echo "Sleeping for $DELAY seconds ..."
    sleep "$DELAY"
done

echo Done